//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RideSharingWPApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RideSharingWPApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my application.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string btnChangePass {
            get {
                return ResourceManager.GetString("btnChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample assumes that people above 18 years of age are eligible to vote..
        /// </summary>
        public static string displayMessage {
            get {
                return ResourceManager.GetString("displayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver&apos;s Information.
        /// </summary>
        public static string driverInformation {
            get {
                return ResourceManager.GetString("driverInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver&apos;s License.
        /// </summary>
        public static string driverLicense {
            get {
                return ResourceManager.GetString("driverLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Lincense&apos;s photo.
        /// </summary>
        public static string driverLincensePhoto {
            get {
                return ResourceManager.GetString("driverLincensePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting day.
        /// </summary>
        public static string headerStartingDay {
            get {
                return ResourceManager.GetString("headerStartingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting time.
        /// </summary>
        public static string headerStartingTime {
            get {
                return ResourceManager.GetString("headerStartingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost....
        /// </summary>
        public static string hintCost {
            get {
                return ResourceManager.GetString("hintCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure point....
        /// </summary>
        public static string hintDeparture {
            get {
                return ResourceManager.GetString("hintDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itinerary description....
        /// </summary>
        public static string hintDescription {
            get {
                return ResourceManager.GetString("hintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination point.....
        /// </summary>
        public static string hintDestination {
            get {
                return ResourceManager.GetString("hintDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance....
        /// </summary>
        public static string hintDistance {
            get {
                return ResourceManager.GetString("hintDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email....
        /// </summary>
        public static string hintInputEmail {
            get {
                return ResourceManager.GetString("hintInputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password....
        /// </summary>
        public static string hintInputPass {
            get {
                return ResourceManager.GetString("hintInputPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string hyperlinkForgotPass {
            get {
                return ResourceManager.GetString("hyperlinkForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have password. Log in now!.
        /// </summary>
        public static string passwordAlready {
            get {
                return ResourceManager.GetString("passwordAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending password for this email.
        /// </summary>
        public static string sendPassword {
            get {
                return ResourceManager.GetString("sendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride Sharing- Your Happiness moment.
        /// </summary>
        public static string slogan {
            get {
                return ResourceManager.GetString("slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride Sharing application.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string tracking {
            get {
                return ResourceManager.GetString("tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID.
        /// </summary>
        public static string txtPersonalID {
            get {
                return ResourceManager.GetString("txtPersonalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string txtPhone {
            get {
                return ResourceManager.GetString("txtPhone", resourceCulture);
            }
        }
    }
}
